apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - applicationdisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - applicationdisruptionbudgets/finalizers
  verbs:
  - update
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - applicationdisruptionbudgets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - nodedisruptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - nodedisruptions/finalizers
  verbs:
  - update
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - nodedisruptions/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: node-disruption-controller
    app.kubernetes.io/part-of: node-disruption-controller
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'