name: Release
on: 
  release:
    types: [published]
jobs:

  build:
    name: Publish artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: make all
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: bin/manager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GHR_PATH: bin/manager

    - name: Login to Github Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile.release
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/$(echo ${{ github.repository }} | cut -d'/' -f2):${{ github.ref_name }}