// Code generated by go-swagger; DO NOT EDIT.

package disruption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/criteo/node-disruption-controller/internal/appmgr"
)

// CancelPreparationReader is a Reader for the CancelPreparation structure.
type CancelPreparationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CancelPreparationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCancelPreparationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCancelPreparationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCancelPreparationOK creates a CancelPreparationOK with default headers values
func NewCancelPreparationOK() *CancelPreparationOK {
	return &CancelPreparationOK{}
}

/*
CancelPreparationOK describes a response with status code 200, with default header values.

Acknowledged.
*/
type CancelPreparationOK struct {
}

// IsSuccess returns true when this cancel preparation o k response has a 2xx status code
func (o *CancelPreparationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cancel preparation o k response has a 3xx status code
func (o *CancelPreparationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cancel preparation o k response has a 4xx status code
func (o *CancelPreparationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this cancel preparation o k response has a 5xx status code
func (o *CancelPreparationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this cancel preparation o k response a status code equal to that given
func (o *CancelPreparationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the cancel preparation o k response
func (o *CancelPreparationOK) Code() int {
	return 200
}

func (o *CancelPreparationOK) Error() string {
	return fmt.Sprintf("[POST /cancel][%d] cancelPreparationOK", 200)
}

func (o *CancelPreparationOK) String() string {
	return fmt.Sprintf("[POST /cancel][%d] cancelPreparationOK", 200)
}

func (o *CancelPreparationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCancelPreparationDefault creates a CancelPreparationDefault with default headers values
func NewCancelPreparationDefault(code int) *CancelPreparationDefault {
	return &CancelPreparationDefault{
		_statusCode: code,
	}
}

/*
CancelPreparationDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type CancelPreparationDefault struct {
	_statusCode int

	Payload appmgr.Error
}

// IsSuccess returns true when this cancel preparation default response has a 2xx status code
func (o *CancelPreparationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this cancel preparation default response has a 3xx status code
func (o *CancelPreparationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this cancel preparation default response has a 4xx status code
func (o *CancelPreparationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this cancel preparation default response has a 5xx status code
func (o *CancelPreparationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this cancel preparation default response a status code equal to that given
func (o *CancelPreparationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the cancel preparation default response
func (o *CancelPreparationDefault) Code() int {
	return o._statusCode
}

func (o *CancelPreparationDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cancel][%d] cancelPreparation default %s", o._statusCode, payload)
}

func (o *CancelPreparationDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cancel][%d] cancelPreparation default %s", o._statusCode, payload)
}

func (o *CancelPreparationDefault) GetPayload() appmgr.Error {
	return o.Payload
}

func (o *CancelPreparationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
