// Code generated by go-swagger; DO NOT EDIT.

package disruption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/criteo/node-disruption-controller/internal/appmgr"
)

// NewCancelPreparationParams creates a new CancelPreparationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCancelPreparationParams() *CancelPreparationParams {
	return &CancelPreparationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCancelPreparationParamsWithTimeout creates a new CancelPreparationParams object
// with the ability to set a timeout on a request.
func NewCancelPreparationParamsWithTimeout(timeout time.Duration) *CancelPreparationParams {
	return &CancelPreparationParams{
		timeout: timeout,
	}
}

// NewCancelPreparationParamsWithContext creates a new CancelPreparationParams object
// with the ability to set a context for a request.
func NewCancelPreparationParamsWithContext(ctx context.Context) *CancelPreparationParams {
	return &CancelPreparationParams{
		Context: ctx,
	}
}

// NewCancelPreparationParamsWithHTTPClient creates a new CancelPreparationParams object
// with the ability to set a custom HTTPClient for a request.
func NewCancelPreparationParamsWithHTTPClient(client *http.Client) *CancelPreparationParams {
	return &CancelPreparationParams{
		HTTPClient: client,
	}
}

/*
CancelPreparationParams contains all the parameters to send to the API endpoint

	for the cancel preparation operation.

	Typically these are written to a http.Request.
*/
type CancelPreparationParams struct {

	/* Body.

	   Disruption
	*/
	Body *appmgr.Disruption

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cancel preparation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CancelPreparationParams) WithDefaults() *CancelPreparationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cancel preparation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CancelPreparationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cancel preparation params
func (o *CancelPreparationParams) WithTimeout(timeout time.Duration) *CancelPreparationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel preparation params
func (o *CancelPreparationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel preparation params
func (o *CancelPreparationParams) WithContext(ctx context.Context) *CancelPreparationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel preparation params
func (o *CancelPreparationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel preparation params
func (o *CancelPreparationParams) WithHTTPClient(client *http.Client) *CancelPreparationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel preparation params
func (o *CancelPreparationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the cancel preparation params
func (o *CancelPreparationParams) WithBody(body *appmgr.Disruption) *CancelPreparationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the cancel preparation params
func (o *CancelPreparationParams) SetBody(body *appmgr.Disruption) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CancelPreparationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
