// Code generated by go-swagger; DO NOT EDIT.

package disruption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/criteo/node-disruption-controller/internal/appmgr"
)

// NewCheckReadinessParams creates a new CheckReadinessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCheckReadinessParams() *CheckReadinessParams {
	return &CheckReadinessParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCheckReadinessParamsWithTimeout creates a new CheckReadinessParams object
// with the ability to set a timeout on a request.
func NewCheckReadinessParamsWithTimeout(timeout time.Duration) *CheckReadinessParams {
	return &CheckReadinessParams{
		timeout: timeout,
	}
}

// NewCheckReadinessParamsWithContext creates a new CheckReadinessParams object
// with the ability to set a context for a request.
func NewCheckReadinessParamsWithContext(ctx context.Context) *CheckReadinessParams {
	return &CheckReadinessParams{
		Context: ctx,
	}
}

// NewCheckReadinessParamsWithHTTPClient creates a new CheckReadinessParams object
// with the ability to set a custom HTTPClient for a request.
func NewCheckReadinessParamsWithHTTPClient(client *http.Client) *CheckReadinessParams {
	return &CheckReadinessParams{
		HTTPClient: client,
	}
}

/*
CheckReadinessParams contains all the parameters to send to the API endpoint

	for the check readiness operation.

	Typically these are written to a http.Request.
*/
type CheckReadinessParams struct {

	/* Body.

	   Disruption
	*/
	Body *appmgr.Disruption

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the check readiness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckReadinessParams) WithDefaults() *CheckReadinessParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the check readiness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckReadinessParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the check readiness params
func (o *CheckReadinessParams) WithTimeout(timeout time.Duration) *CheckReadinessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check readiness params
func (o *CheckReadinessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check readiness params
func (o *CheckReadinessParams) WithContext(ctx context.Context) *CheckReadinessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check readiness params
func (o *CheckReadinessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check readiness params
func (o *CheckReadinessParams) WithHTTPClient(client *http.Client) *CheckReadinessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check readiness params
func (o *CheckReadinessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the check readiness params
func (o *CheckReadinessParams) WithBody(body *appmgr.Disruption) *CheckReadinessParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the check readiness params
func (o *CheckReadinessParams) SetBody(body *appmgr.Disruption) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CheckReadinessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
