// Code generated by go-swagger; DO NOT EDIT.

package disruption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/criteo/node-disruption-controller/internal/appmgr"
)

// CheckReadinessReader is a Reader for the CheckReadiness structure.
type CheckReadinessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckReadinessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCheckReadinessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 425:
		result := NewCheckReadinessStatus425()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCheckReadinessDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCheckReadinessOK creates a CheckReadinessOK with default headers values
func NewCheckReadinessOK() *CheckReadinessOK {
	return &CheckReadinessOK{}
}

/*
CheckReadinessOK describes a response with status code 200, with default header values.

Ready.
*/
type CheckReadinessOK struct {
}

// IsSuccess returns true when this check readiness o k response has a 2xx status code
func (o *CheckReadinessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this check readiness o k response has a 3xx status code
func (o *CheckReadinessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check readiness o k response has a 4xx status code
func (o *CheckReadinessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this check readiness o k response has a 5xx status code
func (o *CheckReadinessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this check readiness o k response a status code equal to that given
func (o *CheckReadinessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the check readiness o k response
func (o *CheckReadinessOK) Code() int {
	return 200
}

func (o *CheckReadinessOK) Error() string {
	return fmt.Sprintf("[POST /ready][%d] checkReadinessOK", 200)
}

func (o *CheckReadinessOK) String() string {
	return fmt.Sprintf("[POST /ready][%d] checkReadinessOK", 200)
}

func (o *CheckReadinessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCheckReadinessStatus425 creates a CheckReadinessStatus425 with default headers values
func NewCheckReadinessStatus425() *CheckReadinessStatus425 {
	return &CheckReadinessStatus425{}
}

/*
CheckReadinessStatus425 describes a response with status code 425, with default header values.

Cannot be processed right now, retry later / after Retry-After value
*/
type CheckReadinessStatus425 struct {

	/* Delay in seconds.
	 */
	RetryAfter int64
}

// IsSuccess returns true when this check readiness status425 response has a 2xx status code
func (o *CheckReadinessStatus425) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check readiness status425 response has a 3xx status code
func (o *CheckReadinessStatus425) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check readiness status425 response has a 4xx status code
func (o *CheckReadinessStatus425) IsClientError() bool {
	return true
}

// IsServerError returns true when this check readiness status425 response has a 5xx status code
func (o *CheckReadinessStatus425) IsServerError() bool {
	return false
}

// IsCode returns true when this check readiness status425 response a status code equal to that given
func (o *CheckReadinessStatus425) IsCode(code int) bool {
	return code == 425
}

// Code gets the status code for the check readiness status425 response
func (o *CheckReadinessStatus425) Code() int {
	return 425
}

func (o *CheckReadinessStatus425) Error() string {
	return fmt.Sprintf("[POST /ready][%d] checkReadinessStatus425", 425)
}

func (o *CheckReadinessStatus425) String() string {
	return fmt.Sprintf("[POST /ready][%d] checkReadinessStatus425", 425)
}

func (o *CheckReadinessStatus425) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Retry-After
	hdrRetryAfter := response.GetHeader("Retry-After")

	if hdrRetryAfter != "" {
		valretryAfter, err := swag.ConvertInt64(hdrRetryAfter)
		if err != nil {
			return errors.InvalidType("Retry-After", "header", "int64", hdrRetryAfter)
		}
		o.RetryAfter = valretryAfter
	}

	return nil
}

// NewCheckReadinessDefault creates a CheckReadinessDefault with default headers values
func NewCheckReadinessDefault(code int) *CheckReadinessDefault {
	return &CheckReadinessDefault{
		_statusCode: code,
	}
}

/*
CheckReadinessDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type CheckReadinessDefault struct {
	_statusCode int

	Payload appmgr.Error
}

// IsSuccess returns true when this check readiness default response has a 2xx status code
func (o *CheckReadinessDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this check readiness default response has a 3xx status code
func (o *CheckReadinessDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this check readiness default response has a 4xx status code
func (o *CheckReadinessDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this check readiness default response has a 5xx status code
func (o *CheckReadinessDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this check readiness default response a status code equal to that given
func (o *CheckReadinessDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the check readiness default response
func (o *CheckReadinessDefault) Code() int {
	return o._statusCode
}

func (o *CheckReadinessDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /ready][%d] checkReadiness default %s", o._statusCode, payload)
}

func (o *CheckReadinessDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /ready][%d] checkReadiness default %s", o._statusCode, payload)
}

func (o *CheckReadinessDefault) GetPayload() appmgr.Error {
	return o.Payload
}

func (o *CheckReadinessDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
