// Code generated by go-swagger; DO NOT EDIT.

package disruption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/criteo/node-disruption-controller/internal/appmgr"
)

// NewCloseDisruptionParams creates a new CloseDisruptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCloseDisruptionParams() *CloseDisruptionParams {
	return &CloseDisruptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCloseDisruptionParamsWithTimeout creates a new CloseDisruptionParams object
// with the ability to set a timeout on a request.
func NewCloseDisruptionParamsWithTimeout(timeout time.Duration) *CloseDisruptionParams {
	return &CloseDisruptionParams{
		timeout: timeout,
	}
}

// NewCloseDisruptionParamsWithContext creates a new CloseDisruptionParams object
// with the ability to set a context for a request.
func NewCloseDisruptionParamsWithContext(ctx context.Context) *CloseDisruptionParams {
	return &CloseDisruptionParams{
		Context: ctx,
	}
}

// NewCloseDisruptionParamsWithHTTPClient creates a new CloseDisruptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCloseDisruptionParamsWithHTTPClient(client *http.Client) *CloseDisruptionParams {
	return &CloseDisruptionParams{
		HTTPClient: client,
	}
}

/*
CloseDisruptionParams contains all the parameters to send to the API endpoint

	for the close disruption operation.

	Typically these are written to a http.Request.
*/
type CloseDisruptionParams struct {

	/* Body.

	   Disruption
	*/
	Body *appmgr.Disruption

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the close disruption params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloseDisruptionParams) WithDefaults() *CloseDisruptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the close disruption params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloseDisruptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the close disruption params
func (o *CloseDisruptionParams) WithTimeout(timeout time.Duration) *CloseDisruptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the close disruption params
func (o *CloseDisruptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the close disruption params
func (o *CloseDisruptionParams) WithContext(ctx context.Context) *CloseDisruptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the close disruption params
func (o *CloseDisruptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the close disruption params
func (o *CloseDisruptionParams) WithHTTPClient(client *http.Client) *CloseDisruptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the close disruption params
func (o *CloseDisruptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the close disruption params
func (o *CloseDisruptionParams) WithBody(body *appmgr.Disruption) *CloseDisruptionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the close disruption params
func (o *CloseDisruptionParams) SetBody(body *appmgr.Disruption) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CloseDisruptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
