// Code generated by go-swagger; DO NOT EDIT.

package disruption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/criteo/node-disruption-controller/internal/appmgr"
)

// NewPrepareApplicationParams creates a new PrepareApplicationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPrepareApplicationParams() *PrepareApplicationParams {
	return &PrepareApplicationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPrepareApplicationParamsWithTimeout creates a new PrepareApplicationParams object
// with the ability to set a timeout on a request.
func NewPrepareApplicationParamsWithTimeout(timeout time.Duration) *PrepareApplicationParams {
	return &PrepareApplicationParams{
		timeout: timeout,
	}
}

// NewPrepareApplicationParamsWithContext creates a new PrepareApplicationParams object
// with the ability to set a context for a request.
func NewPrepareApplicationParamsWithContext(ctx context.Context) *PrepareApplicationParams {
	return &PrepareApplicationParams{
		Context: ctx,
	}
}

// NewPrepareApplicationParamsWithHTTPClient creates a new PrepareApplicationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPrepareApplicationParamsWithHTTPClient(client *http.Client) *PrepareApplicationParams {
	return &PrepareApplicationParams{
		HTTPClient: client,
	}
}

/*
PrepareApplicationParams contains all the parameters to send to the API endpoint

	for the prepare application operation.

	Typically these are written to a http.Request.
*/
type PrepareApplicationParams struct {

	/* Body.

	   Disruption
	*/
	Body *appmgr.Disruption

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the prepare application params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PrepareApplicationParams) WithDefaults() *PrepareApplicationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the prepare application params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PrepareApplicationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the prepare application params
func (o *PrepareApplicationParams) WithTimeout(timeout time.Duration) *PrepareApplicationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the prepare application params
func (o *PrepareApplicationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the prepare application params
func (o *PrepareApplicationParams) WithContext(ctx context.Context) *PrepareApplicationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the prepare application params
func (o *PrepareApplicationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the prepare application params
func (o *PrepareApplicationParams) WithHTTPClient(client *http.Client) *PrepareApplicationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the prepare application params
func (o *PrepareApplicationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the prepare application params
func (o *PrepareApplicationParams) WithBody(body *appmgr.Disruption) *PrepareApplicationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the prepare application params
func (o *PrepareApplicationParams) SetBody(body *appmgr.Disruption) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PrepareApplicationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
