// Code generated by go-swagger; DO NOT EDIT.

package disruption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/criteo/node-disruption-controller/internal/appmgr"
)

// PrepareApplicationReader is a Reader for the PrepareApplication structure.
type PrepareApplicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PrepareApplicationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPrepareApplicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 424:
		result := NewPrepareApplicationFailedDependency()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 425:
		result := NewPrepareApplicationStatus425()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPrepareApplicationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPrepareApplicationOK creates a PrepareApplicationOK with default headers values
func NewPrepareApplicationOK() *PrepareApplicationOK {
	return &PrepareApplicationOK{}
}

/*
PrepareApplicationOK describes a response with status code 200, with default header values.

Accepted, preparation planned.
*/
type PrepareApplicationOK struct {
}

// IsSuccess returns true when this prepare application o k response has a 2xx status code
func (o *PrepareApplicationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this prepare application o k response has a 3xx status code
func (o *PrepareApplicationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this prepare application o k response has a 4xx status code
func (o *PrepareApplicationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this prepare application o k response has a 5xx status code
func (o *PrepareApplicationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this prepare application o k response a status code equal to that given
func (o *PrepareApplicationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the prepare application o k response
func (o *PrepareApplicationOK) Code() int {
	return 200
}

func (o *PrepareApplicationOK) Error() string {
	return fmt.Sprintf("[POST /prepare][%d] prepareApplicationOK", 200)
}

func (o *PrepareApplicationOK) String() string {
	return fmt.Sprintf("[POST /prepare][%d] prepareApplicationOK", 200)
}

func (o *PrepareApplicationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPrepareApplicationFailedDependency creates a PrepareApplicationFailedDependency with default headers values
func NewPrepareApplicationFailedDependency() *PrepareApplicationFailedDependency {
	return &PrepareApplicationFailedDependency{}
}

/*
PrepareApplicationFailedDependency describes a response with status code 424, with default header values.

Unable to accept due to internal constraints.
*/
type PrepareApplicationFailedDependency struct {
}

// IsSuccess returns true when this prepare application failed dependency response has a 2xx status code
func (o *PrepareApplicationFailedDependency) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this prepare application failed dependency response has a 3xx status code
func (o *PrepareApplicationFailedDependency) IsRedirect() bool {
	return false
}

// IsClientError returns true when this prepare application failed dependency response has a 4xx status code
func (o *PrepareApplicationFailedDependency) IsClientError() bool {
	return true
}

// IsServerError returns true when this prepare application failed dependency response has a 5xx status code
func (o *PrepareApplicationFailedDependency) IsServerError() bool {
	return false
}

// IsCode returns true when this prepare application failed dependency response a status code equal to that given
func (o *PrepareApplicationFailedDependency) IsCode(code int) bool {
	return code == 424
}

// Code gets the status code for the prepare application failed dependency response
func (o *PrepareApplicationFailedDependency) Code() int {
	return 424
}

func (o *PrepareApplicationFailedDependency) Error() string {
	return fmt.Sprintf("[POST /prepare][%d] prepareApplicationFailedDependency", 424)
}

func (o *PrepareApplicationFailedDependency) String() string {
	return fmt.Sprintf("[POST /prepare][%d] prepareApplicationFailedDependency", 424)
}

func (o *PrepareApplicationFailedDependency) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPrepareApplicationStatus425 creates a PrepareApplicationStatus425 with default headers values
func NewPrepareApplicationStatus425() *PrepareApplicationStatus425 {
	return &PrepareApplicationStatus425{}
}

/*
PrepareApplicationStatus425 describes a response with status code 425, with default header values.

Cannot be processed right now, retry later / after Retry-After value
*/
type PrepareApplicationStatus425 struct {

	/* Delay in seconds.
	 */
	RetryAfter int64
}

// IsSuccess returns true when this prepare application status425 response has a 2xx status code
func (o *PrepareApplicationStatus425) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this prepare application status425 response has a 3xx status code
func (o *PrepareApplicationStatus425) IsRedirect() bool {
	return false
}

// IsClientError returns true when this prepare application status425 response has a 4xx status code
func (o *PrepareApplicationStatus425) IsClientError() bool {
	return true
}

// IsServerError returns true when this prepare application status425 response has a 5xx status code
func (o *PrepareApplicationStatus425) IsServerError() bool {
	return false
}

// IsCode returns true when this prepare application status425 response a status code equal to that given
func (o *PrepareApplicationStatus425) IsCode(code int) bool {
	return code == 425
}

// Code gets the status code for the prepare application status425 response
func (o *PrepareApplicationStatus425) Code() int {
	return 425
}

func (o *PrepareApplicationStatus425) Error() string {
	return fmt.Sprintf("[POST /prepare][%d] prepareApplicationStatus425", 425)
}

func (o *PrepareApplicationStatus425) String() string {
	return fmt.Sprintf("[POST /prepare][%d] prepareApplicationStatus425", 425)
}

func (o *PrepareApplicationStatus425) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Retry-After
	hdrRetryAfter := response.GetHeader("Retry-After")

	if hdrRetryAfter != "" {
		valretryAfter, err := swag.ConvertInt64(hdrRetryAfter)
		if err != nil {
			return errors.InvalidType("Retry-After", "header", "int64", hdrRetryAfter)
		}
		o.RetryAfter = valretryAfter
	}

	return nil
}

// NewPrepareApplicationDefault creates a PrepareApplicationDefault with default headers values
func NewPrepareApplicationDefault(code int) *PrepareApplicationDefault {
	return &PrepareApplicationDefault{
		_statusCode: code,
	}
}

/*
PrepareApplicationDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type PrepareApplicationDefault struct {
	_statusCode int

	Payload appmgr.Error
}

// IsSuccess returns true when this prepare application default response has a 2xx status code
func (o *PrepareApplicationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this prepare application default response has a 3xx status code
func (o *PrepareApplicationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this prepare application default response has a 4xx status code
func (o *PrepareApplicationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this prepare application default response has a 5xx status code
func (o *PrepareApplicationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this prepare application default response a status code equal to that given
func (o *PrepareApplicationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the prepare application default response
func (o *PrepareApplicationDefault) Code() int {
	return o._statusCode
}

func (o *PrepareApplicationDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /prepare][%d] prepareApplication default %s", o._statusCode, payload)
}

func (o *PrepareApplicationDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /prepare][%d] prepareApplication default %s", o._statusCode, payload)
}

func (o *PrepareApplicationDefault) GetPayload() appmgr.Error {
	return o.Payload
}

func (o *PrepareApplicationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
