// Code generated by go-swagger; DO NOT EDIT.

package disruption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/criteo/node-disruption-controller/internal/appmgr"
)

// NewTerminateDisruptionParams creates a new TerminateDisruptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTerminateDisruptionParams() *TerminateDisruptionParams {
	return &TerminateDisruptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTerminateDisruptionParamsWithTimeout creates a new TerminateDisruptionParams object
// with the ability to set a timeout on a request.
func NewTerminateDisruptionParamsWithTimeout(timeout time.Duration) *TerminateDisruptionParams {
	return &TerminateDisruptionParams{
		timeout: timeout,
	}
}

// NewTerminateDisruptionParamsWithContext creates a new TerminateDisruptionParams object
// with the ability to set a context for a request.
func NewTerminateDisruptionParamsWithContext(ctx context.Context) *TerminateDisruptionParams {
	return &TerminateDisruptionParams{
		Context: ctx,
	}
}

// NewTerminateDisruptionParamsWithHTTPClient creates a new TerminateDisruptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewTerminateDisruptionParamsWithHTTPClient(client *http.Client) *TerminateDisruptionParams {
	return &TerminateDisruptionParams{
		HTTPClient: client,
	}
}

/*
TerminateDisruptionParams contains all the parameters to send to the API endpoint

	for the terminate disruption operation.

	Typically these are written to a http.Request.
*/
type TerminateDisruptionParams struct {

	/* Body.

	   Disruption
	*/
	Body *appmgr.Disruption

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the terminate disruption params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TerminateDisruptionParams) WithDefaults() *TerminateDisruptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the terminate disruption params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TerminateDisruptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the terminate disruption params
func (o *TerminateDisruptionParams) WithTimeout(timeout time.Duration) *TerminateDisruptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the terminate disruption params
func (o *TerminateDisruptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the terminate disruption params
func (o *TerminateDisruptionParams) WithContext(ctx context.Context) *TerminateDisruptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the terminate disruption params
func (o *TerminateDisruptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the terminate disruption params
func (o *TerminateDisruptionParams) WithHTTPClient(client *http.Client) *TerminateDisruptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the terminate disruption params
func (o *TerminateDisruptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the terminate disruption params
func (o *TerminateDisruptionParams) WithBody(body *appmgr.Disruption) *TerminateDisruptionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the terminate disruption params
func (o *TerminateDisruptionParams) SetBody(body *appmgr.Disruption) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TerminateDisruptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
