// Code generated by go-swagger; DO NOT EDIT.

package appmgr

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Disruption Disprution describes a disruption of nodes by a given source.
//
// swagger:model Disruption
type Disruption struct {

	// Source of the disruption
	// Example: maintenance-manager
	CreatedBy string `json:"createdBy,omitempty"`

	// When the disruption was created
	// Format: date-time
	CreationDate strfmt.DateTime `json:"creationDate,omitempty"`

	// Start date + duration pre-calculated
	// Format: date-time
	DeadlineDate strfmt.DateTime `json:"deadlineDate,omitempty"`

	// For how long in seconds the disruption is expected to last after the start date.
	// Example: 3600
	Duration int64 `json:"duration,omitempty"`

	// Human readable identifier of the disruption
	// Example: hw-maint-123
	Name string `json:"name,omitempty"`

	// Nodes affected by this disruption
	// Example: ["hello.example.com"]
	Nodes []string `json:"nodes"`

	// Expected start date of the disruption
	// Format: date-time
	StartDate strfmt.DateTime `json:"startDate,omitempty"`

	// Type of disruption
	// Example: decommission
	Type string `json:"type,omitempty"`

	// Unique ID for this disruption
	// Example: f45ac82c-7571-4770-8de1-dfdb0bf598de
	UID string `json:"uid,omitempty"`
}

// Validate validates this disruption
func (m *Disruption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeadlineDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Disruption) validateCreationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CreationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("creationDate", "body", "date-time", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Disruption) validateDeadlineDate(formats strfmt.Registry) error {
	if swag.IsZero(m.DeadlineDate) { // not required
		return nil
	}

	if err := validate.FormatOf("deadlineDate", "body", "date-time", m.DeadlineDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Disruption) validateStartDate(formats strfmt.Registry) error {
	if swag.IsZero(m.StartDate) { // not required
		return nil
	}

	if err := validate.FormatOf("startDate", "body", "date-time", m.StartDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this disruption based on context it is used
func (m *Disruption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Disruption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Disruption) UnmarshalBinary(b []byte) error {
	var res Disruption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
