// Code generated by go-swagger; DO NOT EDIT.

package appmgr

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Error Error details when available
// Example: unable to contact internal tools
//
// swagger:model Error
type Error string

// Validate validates this error
func (m Error) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this error based on context it is used
func (m Error) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
